version: "3"

services:
  video-api:
    container_name: video-api
    build:
      context: ./video-api
      dockerfile: Dockerfile
    volumes:
      - ./video-api:/home/app
    tty: true
    stdin_open: true
    command: bash


  storage-api:
    container_name: storage-api
    build:
      context: ./storage-api
      dockerfile: Dockerfile
    depends_on:
      minio:
        condition: service_started
    ports:
      - 8080:8080
    env_file:
      - ./storage-api/.env
    volumes:
      - ./storage-api:/home/app

  minio:
    image: minio/minio:edge
    volumes:
        - ./vdata/minio:/data
    env_file:
      - ./conf/.minio.env
    ports:
        - 9000:9000
        - 9001:9001
    command: server  /data --console-address ":9001"
