version: "3"

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway:/home/app
    env_file:
      - ./gateway/.env
    ports:
      - 8082:8080

  
  queue:
    container_name: queue
    healthcheck:
      test: rabbitmq-diagnostics -q ping
    image: rabbitmq:3.11.15-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./conf/.rabbitmq.env
  

  video-api:
    container_name: video-api
    build:
      context: ./video-api
      dockerfile: Dockerfile
    volumes:
      - ./video-api:/home/app
    ports:
      - 8081:8080


  file-storage-api:
    container_name: file-storage-api
    build:
      context: ./file-storage-api
      dockerfile: Dockerfile
    depends_on:
      minio:
        condition: service_started
    ports:
      - 8080:8080
    env_file:
      - ./file-storage-api/.env
    volumes:
      - ./file-storage-api:/home/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules

  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z.fips
    volumes:
        - ./vdata/minio:/data
    env_file:
      - ./conf/.minio.env
    ports:
        - 9000:9000
        - 9001:9001
    command: server  /data --console-address ":9001"
