version: "3"

services:
  video-api:
    container_name: video-api
    build:
      context: ./video-api
      dockerfile: Dockerfile
    volumes:
      - ./video-api:/home/app
    ports:
      - 8081:8080


  storage-api:
    container_name: storage-api
    build:
      context: ./storage-api
      dockerfile: Dockerfile
    depends_on:
      minio:
        condition: service_started
    ports:
      - 8080:8080
    env_file:
      - ./storage-api/.env
    volumes:
      - ./storage-api:/home/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules

  minio:
    image: minio/minio:edge
    volumes:
        - ./vdata/minio:/data
    env_file:
      - ./conf/.minio.env
    ports:
        - 9000:9000
        - 9001:9001
    command: server  /data --console-address ":9001"
